### PR TITLE
Add validation of Kubernetes feature gates

### PR DESCRIPTION
**Pull request by stoyanr**
**How to categorize this PR?**

/area usability
/area ops-productivity
/kind enhancement
/platform openstack

**What this PR does / why we need it**:
Adds validation of Kubernetes feature gates (in `CloudControllerManager` field of the `ControlPlaneConfig` custom resource), as requested in https://github.com/gardener/gardener/issues/3987 and https://github.com/gardener/gardener-extension-provider-gcp/issues/263. Similar to https://github.com/gardener/gardener-extension-provider-gcp/pull/280 but for openstack.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener-extension-provider-gcp/issues/263 for openstack.

**Special notes for your reviewer**:

* Also vendors g/g v1.24.1-0.20210608063816-580010846480 to be able to use the `ValidateFeatureGates` function.

**Release note**:

```other operator
When creating or updating shoots, any Kubernetes feature gates mentioned are validated against the Kubernetes version. If any feature gates are unknown or not supported in the Kubernetes version, the validation fails.
```

### CODE REVIEW

**Review by rfranzke — APPROVED** [review]
/lgtm
/invite @dkistner @kon-angelo

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Pull request merged**
