### PR TITLE
Enable propagating pod routes to nodes without overlay network

### PR DESCRIPTION
**Pull request by ScheererJ**
**How to categorize this PR?**

/area networking
/kind enhancement
/kind cleanup
/platform openstack

**What this PR does / why we need it**:
Enable propagating pod routes to nodes without overlay network.

Some infrastructures, most notably `openstack`, may implement routing in the virtual network by moving all traffic via a routing component. This can introduce additional latency and will eventually become a bottleneck. In case the network is sufficiently capable of using a "short-cut" by applying local routes on the nodes, it can be desirable to do so.

This change allows to trigger propagation of pod routes to all nodes via an option in the networking configuration.

**Which issue(s) this PR fixes**:
None.

**Special notes for your reviewer**:
Related changes:
https://github.com/gardener/gardener-extension-networking-calico/pull/285
https://github.com/gardener/gardener-extension-networking-cilium/pull/203

As a side-effect, this change also revendors gardener/gardener to v1.76.0.

**Release note**:

```other operator
Enable propagating pod routes to nodes without overlay network
```

### CODE REVIEW

**Comment by kon-angelo** [comment]
@ScheererJ can you run `make generate` again ?

**Comment by ScheererJ** [comment]
> @ScheererJ can you run `make generate` again ?

Done.

**Comment by ScheererJ** [comment]
@kon-angelo Now, the pull request should be in a review-able state. Please take a look.

**Review by kon-angelo — COMMENTED** [review]
/lgtm but you need to rebase the PR

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Pull request merged**
