### PR TITLE
Allow configuration of etcd storage class reclaimPolicy

### PR DESCRIPTION
**Pull request by elenz97**
Since the `ReclaimPolicy` field is exposed via `StorageClassDefinition` [here](https://github.com/gardener/gardener-extension-provider-openstack/blob/47a016f1059849091c63ce842616ce060349e901/pkg/apis/openstack/types_cloudprofile.go#L224), making it configurable should be reasonable.

/area control-plane
/area usability

```other user
Allow configuration of etcd storage class reclaimPolicy
```

### CODE REVIEW

**Comment by gardener-robot-ci-1** [comment]
Thank you @elenz97 for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Comment by kon-angelo** [comment]
@elenz97 can you run `make generate` and update the PR ?

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Comment by kon-angelo** [comment]
@elenz97 I guess you need to rebase first

**Comment by elenz97** [comment]
Should be rebased on the current master now (synced my fork accordingly).

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Pull request merged**
