### PR TITLE
[ci:component:github.com/gardener/machine-controller-manager:v0.39.0->v0.40.0]

### PR DESCRIPTION
**Pull request by gardener-robot-ci-3**
**Release Notes*:
``` feature user github.com/gardener/machine-controller-manager #629 @prashanth26
Increase default concurrent object syncs to 50 to allow more concurrent reconciles to occur.
```

``` feature user github.com/gardener/machine-controller-manager #627 @prashanth26
Machine rollouts are now more as desired with the number of replicas always maintained to `desired + maxSurge`. Earlier machines in termination were left out of this calculation but now is considered with this change.
```

``` bugfix operator github.com/gardener/machine-controller-manager #627 @prashanth26
Avoids blocking of drain call when the buffer is full for the volumeAttachmentHandlers.
```

``` feature developer github.com/gardener/machine-controller-manager #620 @AxiomSamarth
Replace integration test with unit test to test the functionality to freeze MachineSet
```

``` bugfix developer github.com/gardener/machine-controller-manager #617 @himanshu-kun
Test framework now fetches secrets from the correct (control) APIServer while running tests.
```

``` other operator github.com/gardener/machine-controller-manager #612 @himanshu-kun
Nodes attached to the cluster without MCM support are now annotated with `"node.machine.sapcloud.io/notManagedByMCM": "1"`. This is then ignored by the MCM for further processing.
```

``` breaking operator github.com/gardener/machine-controller-manager #608 @prashanth26
Draining of pods with PVs (Persistent Volume) now waits for re-attachment of PV on a different node when `volumeAttachments` support is enabled on the cluster. Else it falls back to the default PV reattachment timeout value configured. The default value is `90s` and this can be overwritten via the `machine-pv-reattach-timeout` flag. Please enable permissions to allow listing of `volumeAttachments` resource while importing these changes.
```

``` feature operator github.com/gardener/machine-controller-manager #593 @AxiomSamarth
Finalizers will be added to the MachineClass which is used by at least one machine. Machines whose backing MachineClass does not have finalizers shall not be reconciled.
```

### CODE REVIEW

**Review by prashanth26 — APPROVED** [review]
MCM RBACs are to be updated with the MC-provider release, not a blocker for this PR. This PR can be merged. 

/lgtm

**Review by rfranzke — APPROVED** [review]
/lgtm
/hold due to ongoing release validation
/assign @dkistner @kon-angelo

**Review by dkistner — APPROVED** [review]
/lgtm

**Pull request merged**
