### PR TITLE
add manila labels

### PR DESCRIPTION
**Pull request by kon-angelo**
**How to categorize this PR?**

/area control-plane
/kind enhancement
/platform openstack

**What this PR does / why we need it**:
Allows autoscaling for manila volumes

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Add manila topology labels to machines. This enables scaling from 0 for pods depending on manila volumes.
```

### CODE REVIEW

**Review by ScheererJ — APPROVED** [review]
/lgtm

**Comment by ScheererJ** [comment]
Please check the tests, though.

**Comment by kon-angelo** [comment]
@ScheererJ tests have been checked.

**Review by ScheererJ — APPROVED** [review]
/lgtm

**Pull request merged**
