### PR TITLE
Revendor `gardener/gardener@v1.40.1`

### PR DESCRIPTION
**Pull request by dkistner**
**How to categorize this PR?**
/kind enhancement
/platform openstack
/merge squash

**What this PR does / why we need it**:
Revendor `gardener/gardener@v1.40.1` dependency.
This will include an upgrade to `ginkgo` v2.

**Release note**:
```other operator
NONE
```

### CODE REVIEW

**Comment by dkistner** [comment]
Integration test locally succeeded.

**Review by rfranzke — APPROVED** [review]
/lgtm
/cc @timebertt

**Comment by timebertt** [comment]
Don't wait for me :)
/needs rebase

**Comment by dkistner** [comment]
Revendored to `g/g@v1.40.1`. Integration test passed locally.

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Review by kon-angelo — APPROVED** [review]

**Pull request merged**
