### PR TITLE
Add possibility to set etcd StorageClass parameters

### PR DESCRIPTION
**Pull request by Kumm-Kai**
**How to categorize this PR?**

/kind enhancement
/platform openstack

**What this PR does / why we need it**:
This PR adds the ability to set StorageClass parameters for the etcd StorageClass

**Release note**:

```other operator
Parameters of the etcd StorageClass can now be set
```

### CODE REVIEW

**Comment by gardener-robot-ci-2** [comment]
Thank you @Kumm-Kai for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Review by dkistner — APPROVED** [review]
/lgtm

**Review by dkistner — APPROVED** [review]

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Pull request merged**
