### PR TITLE
Inject infrastructure credentials via secret references

### PR DESCRIPTION
**Pull request by timebertt**
**How to categorize this PR?**

/area security quality
/kind cleanup
/priority normal
/platform openstack

**What this PR does / why we need it**:

Currently, the infrastructure actuator injects the terraform variables (infrastructure credentials) by directly setting the environment variables values on the terraformer `PodSpec`.
This is not acceptable from a security point-of-view, hence we switch to env vars with secret references.

Also, it fixes the broken infrastructure `TestDefinition` (cc @prashanth26 @DockToFuture).

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
- ✅ depends on https://github.com/gardener/gardener/pull/3204

/invite @ThormaehlenFred 

**Release note**:

```noteworthy operator
The infrastructure actuator is now injecting infrastructure credentials into the terraformer `PodSpec` via secret references instead of plain env var values.
```

### CODE REVIEW

**Comment by timebertt** [comment]
Vendored `g/g@v1.13.0`, `k/*@v0.18.10` and rebased.
/ready
/test-single

**Review by rfranzke — APPROVED** [review]
/lgtm

**Pull request merged**
