### PR TITLE
use go templates for terraform

### PR DESCRIPTION
**Pull request by kon-angelo**
**How to categorize this PR?**

/area control-plane
/kind cleanup
/platform openstack

**What this PR does / why we need it**:
Replaces openstack-infra helm chart with native go templates

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Replace infrastructure's terraform helm chart with native go templates. 
```

### CODE REVIEW

**Review by timebertt — APPROVED** [review]
Very nice, thank you!
/lgtm

**Review by dkistner — APPROVED** [review]
/lgtm

**Review by rfranzke — APPROVED** [review]

**Pull request merged**
