### PR TITLE
CSI migration beginning with 1.19, convert cloud-provider configmap into secret, remove zone from ControlPlaneConfig

### LINKED ISSUE #1: Adopt CSI for OpenStack extension beginning with Kubernetes 1.19
In order to fix gardener/gardener-extensions#200 and proceed with gardener/gardener-extensions#154 we need to enable the OpenStack CSI in the OpenStack provider.

### LINKED ISSUE #61: Remove zone from ControlPlaneConfig
**What would you like to be added**:
The `zone` field should be removed from the `ControlPlaneConfig`. It was taken over during extensibility from the in-tree behaviour, but it is not needed. In fact, it only influences the `zone` parameter in the default `StorageClass` that gets installed to the shoot cluster, though, this does not work well with multi-zone shoots. The default behaviour of the Cinder volume plugin - if no `zone` parameter is specified - is to randomize the zones.

**Why is this needed**:
Better default configuration for OpenStack shoots.

### PR DESCRIPTION
**Pull request by rfranzke**
**What this PR does / why we need it**:
This PR adds support for CSI (+ migration for existing clusters).
CSI will be used for 1.19 shoots. Older shoots will keep using the in-tree legacy volume provisioner.
Also, it converts the cloud-provider `ConfigMap` to a `Secret`.
Also, it removes the `zone` field from the `ControlPlaneConfig`.

**Which issue(s) this PR fixes**:
Fixes #1 
Fixes #61

**Special notes for your reviewer**:
OpenStack CSI migration is still alpha with 1.18 but will be promoted to beta with 1.19. When we work on 1.19 support for OpenStack we should revisit the CSI and probably update the image versions.

**Release note**:

```noteworthy user
The `zone` field in the `ControlPlaneConfig` has been deprecated and will be removed in a future version. It is no longer required to set and has no effect anymore. Consider updating your deployment manifests.
```
```noteworthy operator
The `cloud-provider-config-cloud-controller-manager` has been renamed to `cloud-provider-config` and is now a `Secret` instead of a `ConfigMap`. The `cloud-provider-config-kube-controller-manager` has been renamed to `cloud-provider-disk-config` and is now a `Secret` instead of a `ConfigMap`.
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
> I will play with it asap.

I played with pvcs and volumesnapshots, it worked well.

**Comment by rfranzke** [comment]
Thanks @ialidzhikov!
Anybody else planning to review it? If not, I want to merge it tomorrow.

**Comment by rfranzke** [comment]
@tim-ebert does it mean you won't review it or whether you'd want me to wait? 😄

**Comment by tim-ebert** [comment]
Sorry, that was ambiguous. 
I won’t review😅

**Comment by gardener-botmanager** [comment]
@rfranzke Command /merge is not known.

**Pull request merged**
