### PR TITLE
add convenient description to security group rules

### PR DESCRIPTION
**Pull request by nschad**
**How to categorize this PR?**
/area networking
/kind enhancement
/platform openstack

Adds convenient descriptions to security group rules in terraformer.

**What this PR does / why we need it**:

N.A.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other developer
Added description to openstack security group rules.
```

### CODE REVIEW

**Comment by kon-angelo** [comment]
@nschad looks good. Could you go through the trouble of adding the same description to the definitions in https://github.com/gardener/gardener-extension-provider-openstack/blob/05711993d1f0fd0f8e7199c76dcbdfc4cb08e93b/pkg/controller/infrastructure/infraflow/reconcile.go#L380 ?

**Comment by nschad** [comment]
> @nschad looks good. Could you go through the trouble of adding the same description to the definitions in
> 
> https://github.com/gardener/gardener-extension-provider-openstack/blob/05711993d1f0fd0f8e7199c76dcbdfc4cb08e93b/pkg/controller/infrastructure/infraflow/reconcile.go#L380
> 
> ?

Done. I've noticed that the `reconcile.go` has an extra secgroup rule for outgoing IPv6 but 🤷 we will soon ™️ implement ipv6 anyway soo....

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Pull request merged**
