### PR TITLE
make `ClusterFilter` and `StorageClass` toggable in helm-chart

### PR DESCRIPTION
**Pull request by nschad**
**How to categorize this PR?**
/area control-plane
/kind enhancement
/platform openstack

**What this PR does / why we need it**:

Allows the operator to configure whether he wants to deploy the `ClusterFilters` or `StorageClass` by default. This is required for us as we currently still have 2 Extensions registered on the same `type`. Therefore we need to be able to configure in one extension, that certain things don't need to be deployed.

To not change anything the default is implemented as always deploy just like before.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```feature operator
Allows the operator to configure whether he wants to deploy the standard ClusterFilters and/or StorageClass
```

### CODE REVIEW

**Comment by gardener-robot-ci-2** [comment]
Thank you @nschad for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Comment by kon-angelo** [comment]
@nschad can you run `make generate` ?

**Comment by nschad** [comment]
> @nschad can you run `make generate` ?

Done.

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Pull request merged**
