### PR TITLE
Align provider name with naming convension

### PR DESCRIPTION
**Pull request by prashanth26**
**How to categorize this PR?**

/area dev-productivity
/kind cleanup
/platform openstack

**What this PR does / why we need it**:
The provider name should match with the convension used by [machine controller openstack here](https://github.com/gardener/machine-controller-manager-provider-openstack/blob/master/pkg/driver/utils.go#L23). Specially with [this change](https://github.com/gardener/machine-controller-manager-provider-openstack/pull/19) coming in. 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by kon-angelo** [comment]
@prashanth26 I am a bit conflicted because in other providers e.g. [azure](https://github.com/gardener/gardener-extension-provider-azure/pull/257/files) , [aws](https://github.com/gardener/gardener-extension-provider-aws/blob/32dcc7ef152998192c9219bc85e5d693f0f5c99b/charts/internal/machineclass/templates/machineclass.yaml#L46), gcp we use camelcase. These were my point of reference too for the initial naming.

I would suggest we update the respective openstack-mcm PR to match that (plus it requires only one change to be commited). My argument is solely about consistency between the providers. 

If you feel a strong preference towards the lowercase we can go ahead and merge it though.

**Comment by prashanth26** [comment]
> @prashanth26 I am a bit conflicted because in other providers e.g. [azure](https://github.com/gardener/gardener-extension-provider-azure/pull/257/files) , [aws](https://github.com/gardener/gardener-extension-provider-aws/blob/32dcc7ef152998192c9219bc85e5d693f0f5c99b/charts/internal/machineclass/templates/machineclass.yaml#L46), gcp we use camelcase. These were my point of reference too for the initial naming.
> 
> I would suggest we update the respective openstack-mcm PR to match that (plus it requires only one change to be commited). My argument is solely about consistency between the providers.
> 
> If you feel a strong preference towards the lowercase we can go ahead and merge it though.

💯 . Let's change the providerName to match with this -https://github.com/gardener/gardener-extension-provider-openstack/pull/262/files#diff-9b4849c5f886d8c9282bd3836aecbc442f1dc76bf89e3f7d91183b9758e0e646L25. 
cc: @AxiomSamarth

**Pull request closed without merging**
