### PR TITLE
get existing router via ID

### LINKED ISSUE #546: `make integration-test-infra` fails
**How to categorize this issue?**

/area quality
/area dev-productivity
/kind bug
/kind regression
/platform openstack

**What happened**:
```
% make integration-test-infra

  Unexpected error:
      <*helper.ErrorWithCodes | 0xc000be7b00>: {
          err: <*fmt.wrapError | 0xc000277460>{
              msg: "Error while waiting for Infrastructure openstack--infra-it--h2ttb/infrastructure to become ready: error during reconciliation: Error reconciling infrastructure: failed to apply the terraform config: Terraform execution for command 'apply' could not be completed:\n\n* Reference to undeclared resource\n  on main.tf line 114, in output \"router_ip\":\n 114:   value = openstack_networking_router_v2.router.external_fixed_ip[0].ip_address\nA managed resource \"openstack_networking_router_v2\" \"router\" has not been\ndeclared in the root module.",
              err: <*helper.ErrorWithCodes | 0xc000be7ad0>{
                  err: <*errors.errorString | 0xc000eca1d0>{
                      s: "error during reconciliation: Error reconciling infrastructure: failed to apply the terraform config: Terraform execution for command 'apply' could not be completed:\n\n* Reference to undeclared resource\n  on main.tf line 114, in output \"router_ip\":\n 114:   value = openstack_networking_router_v2.router.external_fixed_ip[0].ip_address\nA managed resource \"openstack_networking_router_v2\" \"router\" has not been\ndeclared in the root module.",
                  },
                  codes: nil,
              },
          },
          codes: nil,
      }
      Error while waiting for Infrastructure openstack--infra-it--h2ttb/infrastructure to become ready: error during reconciliation: Error reconciling infrastructure: failed to apply the terraform config: Terraform execution for command 'apply' could not be completed:

      * Reference to undeclared resource
        on main.tf line 114, in output "router_ip":
       114:   value = openstack_networking_router_v2.router.external_fixed_ip[0].ip_address
      A managed resource "openstack_networking_router_v2" "router" has not been
      declared in the root module.
  occurred
  In [It] at: /go/src/github.com/gardener/gardener-extension-provider-openstack/test/integration/infrastructure/infrastructure_test.go:306
```

The regression is introduced with https://github.com/gardener/gardener-extension-provider-openstack/pull/520.

**What you expected to happen**:
`make integration-test-infra` to succeed. I believe this is not only a bug with the test but a real issue for the case when existing network and router are used.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant):
- Extension version: b390fb780945716b055fb13175c77dee0e39df46
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by breuerfelix**
**How to categorize this PR?**
/area quality
/kind bug
/platform openstack

**What this PR does / why we need it**:
See #546 

**Which issue(s) this PR fixes**:
Fixes #546 

**Special notes for your reviewer**:

**Release note**:
```other operator
NONE
```

### CODE REVIEW

**Review by timebertt — COMMENTED** [review]
/lgtm
/ok-to-test

**Review by kon-angelo — APPROVED** [review]
with the latest commit the tests seem to work. Let's go with that.

/lgtm

**Pull request merged**
