### PR TITLE
[ci:component:github.com/gardener/terraformer:v2.15.0->v2.16.0]

### PR DESCRIPTION
**Pull request by gardener-robot-ci-2**
**Release Notes**:
``` other operator github.com/gardener/terraformer #107 @stoyanr
terraform has been upgraded to 0.15.5
```

### CODE REVIEW

**Review by ialidzhikov — APPROVED** [review]
/lgtm
/invite @dkistner @kon-angelo @stoyanr

**Comment by dkistner** [comment]
@ialidzhikov Did you run the integration test locally with success?

**Comment by ialidzhikov** [comment]
> @ialidzhikov Did you run the integration test locally with success?

No, I didn't.

**Comment by dkistner** [comment]
Thanks running them now.

**Review by dkistner — APPROVED** [review]
Test passed locally.

/lgtm

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Pull request merged**
