### PR TITLE
Switch to kaniko oci builder

### PR DESCRIPTION
**Pull request by ialidzhikov**
Similar to https://github.com/gardener/gardener-extension-provider-aws/pull/281

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by vpnachev — APPROVED** [review]
/lgtm

**Comment by ialidzhikov** [comment]
Hold until the issue for image pull from containerd is resolved - ref https://github.com/gardener/replica-reloader/issues/6.

/hold

**Comment by ialidzhikov** [comment]
Unhold as the above issue is resolved.

/unhold

**Comment by ialidzhikov** [comment]
Can someone from the repository admins help making the `concourse-ci/build_oci_image_gardener-extension-provider-openstack` and `concourse-ci/build_oci_image_gardener-extension-validator-openstack` checks required (and `concourse-ci/publish` is no longer required)? Thanks in advance!

**Pull request merged**
