### PR TITLE
[GEP-18] Revendor `gardener/gardener@v1.45`, cleanup token projection artefacts, adapt to new secrets manager

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area security
/kind enhancement
/platform openstack

**What this PR does / why we need it**:

- Vendors g/g and adapts to all breaking changes introduced by https://github.com/gardener/gardener/pull/5803
- Cleans up a lot of migration code around moving to short-lived serviceaccount tokens introduced with #369
- Adapts this extension to the new secrets manager, which makes it ready for supporting the shoot CA rotation feature

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/3292

**Special notes for your reviewer**:

Use the dedicated commits, otherwise this PR is pretty much unreviewable.

Based on https://github.com/gardener/gardener-extension-provider-aws/pull/538 (thanks @timebertt for structuring it so well).

**Release note**:

```breaking operator
This extension is only compatible with Gardener versions `>= v1.37`.
```
```feature operator
This extension is prepared to support the Shoot CA rotation feature ([GEP-18](https://github.com/gardener/gardener/issues/3292)).
```

### CODE REVIEW

**Review by timebertt — APPROVED** [review]
Thank you!
/lgtm

**Review by kris94 — COMMENTED** [review]
/lgtm

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Pull request merged**
