### PR TITLE
Deserialize custom resources with EnableStrict

### PR DESCRIPTION
**Pull request by stoyanr**
**How to categorize this PR?**

/area control-plane
/kind enhancement
/priority 3
/platform openstack

**What this PR does / why we need it**:
* Adds the `EnableStrict` option to all places where a codec factory is created, to ensure that extension resource configs are always deserialized in "strict" mode. This means that resources with fields that are not allowed by the API schema will be rejected by validation and will cause errors (categorized as `ERR_CONFIGURATION_PROBLEM`) during reconciliation as well.
* Vendors g/g 1.20.0 (includes https://github.com/gardener/gardener/pull/3804) to ensure that a strict decoder is used also for `ControlPlaneConfig` and `WorkerConfig`, and errors are correctly categorized.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener-extension-provider-azure/pull/270, see also https://github.com/gardener/gardener-extension-provider-azure/pull/271 and https://github.com/gardener/gardener-extension-provider-gcp/pull/249.

**Special notes for your reviewer**:

**Release note**:

```breaking user
Extension resource configs (`InfrastructureConfig`, `ControlPlaneConfigs`, `WorkerConfig`) are now deserialized in "strict" mode, including during validation by the admission webhook. This means that resources with fields that are not allowed by the API schema will be rejected by validation. Creating new shoots containing such resources will not be possible, and reconciling existing shoots will fail with an appropriate error until you manually update the shoot to make sure any extension resource configs contained in it are valid.
```

### CODE REVIEW

**Comment by rfranzke** [comment]
@dkistner @kon-angelo should we hold this PR? Are you validating a release?

**Comment by kon-angelo** [comment]
/hold

@rfranzke  Yes we are validating a release. We can merge this in the coming days

**Review by ialidzhikov — CHANGES_REQUESTED** [review]
The TestDefinitions need an update as well.

```diff
diff --git a/.test-defs/infrastructure-test.yaml b/.test-defs/infrastructure-test.yaml
index 341b20dd..dd7f648c 100644
--- a/.test-defs/infrastructure-test.yaml
+++ b/.test-defs/infrastructure-test.yaml
@@ -19,4 +19,4 @@ spec:
     --region="$REGION"
     --tenant-name="$TENANT_NAME"
     --user-name="$USER_NAME"
-  image: eu.gcr.io/gardener-project/3rd/golang:1.15.7
+  image: eu.gcr.io/gardener-project/3rd/golang:1.16.3
diff --git a/.test-defs/provider-openstack.yaml b/.test-defs/provider-openstack.yaml
index d742f7bc..31820e6e 100644
--- a/.test-defs/provider-openstack.yaml
+++ b/.test-defs/provider-openstack.yaml
@@ -16,4 +16,4 @@ spec:
     --loadbalancer-provider=$LOADBALANCER_PROVIDER
     --network-worker-cidr=$NETWORK_WORKER_CIDR

-  image: eu.gcr.io/gardener-project/3rd/golang:1.15.7
+  image: eu.gcr.io/gardener-project/3rd/golang:1.16.3
```

**Comment by stoyanr** [comment]
> The TestDefinitions need an update as well.

Done

**Comment by rfranzke** [comment]
Can you please revendor the `v1.20.0` tag now that it's released?

**Comment by stoyanr** [comment]
> Can you please revendor the `v1.20.0` tag now that it's released?

Done

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Comment by rfranzke** [comment]
Thanks @stoyanr, can you check why the `verify` step is failing?

**Pull request merged**
